### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mohanakrishnag** [kkotupalli/JS-HW-1#1]
@kkotupalli  Please look into the following comments.

**WordCount**

1. Use proper indentation for each line of code.
2. There should be only one return statement in a function.
3. Remove the commented code.

**Middlecharacter**

1. Use proper indentation for each line of code.
2. Reduce the repeated code.
3.  What if the wordLength / 2 returns 1.5, 2.5,3.5 and all.

**TransportationOnVacation**

1.  Use proper indentation for each line of code.

**Comment by kkotupalli** [comment]
I have updated the code as per the above comments.Please review.
