### ISSUE TITLE
Hw-3 Review

### ISSUE THREAD

**Issue by mohanakrishnag** [kkotupalli/JS-HW-1#3]
**ApplyWithNew.js**
This implementation is wrong. please go through the Instructions of the kata in the Codewars site.
http://www.codewars.com/kata/new-with-apply/train/javascript
there it self it was written as
new operator is evil because it produces a highly coupled code, difficult to maintain and test.
Some patterns to reduce coupling are object factories or dependency injection.

**extractnestedobjectreference.js**
Looks good, Instead we can use while loop also 

Following task is not yet implemented
http://www.codewars.com/kata/using-closures-to-share-class-state

Please let me know if you have any questions.

**Comment by kkotupalli** [comment]
updated the code please review
